### ISSUE TITLE
index error with the latest bedtools jaccard?

### ISSUE THREAD

**Issue by jakebiesinger** [brentp/shuffler#4]
Hi Brent,

I'm sure this package is very alpha, but it looks pretty slick and I'm trying it out for a recent project.

It seems bedtools jaccard has changed its API recently.  Using the latest github version of bedtools, I get the following error:

```
intersection    jaccard n_intersections
Traceback (most recent call last):
  File "/data/apps/enthought_python/7.3.2/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/data/apps/enthought_python/7.3.2/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/data/users/wbiesing/lib/python2.7/site-packages/shuffler/__main__.py", line 249, in <module>
    main()
  File "/data/users/wbiesing/lib/python2.7/site-packages/shuffler/__main__.py", line 77, in main
    shuffle(args)
  File "/data/users/wbiesing/lib/python2.7/site-packages/shuffler/__main__.py", line 233, in shuffle
    res = s.run(command=command, sims=True)
  File "/data/users/wbiesing/lib/python2.7/site-packages/shuffler/shuffler.py", line 127, in run
    self.obs = self.value_fn(nopen("|%s" % (command % args)))
  File "/data/users/wbiesing/lib/python2.7/site-packages/shuffler/shuffler.py", line 34, in jaccard_values
    (int(row[0]), float(row[2]), int(row[3]))))
IndexError: list index out of range
```

bedtools apparently no longer outputs a fourth column. `cat`ing the input file for your `jaccard_values` function looks something like this:

```
intersection     union   jaccard
249      5796772 4.29549e-05
```

So it looks like the reporting order is also different.

Do you have a recommended version of bedtools to run against?

Thanks!

**Comment by jakebiesinger** [comment]
Well, crud.  Turns out my PATH was pointing to an older bedtools after all.  Nevermind.

**Comment by brentp** [comment]
phew! although that code is a bit fragile as written. i'll have a look at making it more robust or at least friendly.
